#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
npm run format
npx vitest run --coverage
npm run make-badges
npx generate-license-file --input package.json --output THIRD-PARTY-NOTICES --overwrite